In [1]:
from numpy import *

In [2]:
a = array([1,2,3],float)

In [3]:
print(a)

[1. 2. 3.]


In [7]:
b=array([[1,2,3],[4,5,6],[7,8,9]],float)

In [8]:
for i in range(3):
    print b[i]

[1. 2. 3.]
[4. 5. 6.]
[7. 8. 9.]


In [9]:
Z=zeros((3,3),float)

In [10]:
print Z

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
O=ones((3,3),float)

In [12]:
print O

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print diagonal(b)

[1. 5. 9.]


In [14]:
trace(b)

15.0

In [15]:
A=identity(3)

In [16]:
print A

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
